version: "3"
services:
  app:
    image: test
    ports:
      - 8081:8080
    environment:
      DAV_NOAUTH: 0
      DAV_USERNAME: webdav
      DAV_PASSWORD: webdav
      DAV_BASEURL: https://storage.glavpodcast.com
    volumes:
      - data:/data
      - conf:/etc/webdav
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: webdav
      MYSQL_USER: webdav
      MYSQL_PASSWORD: webdav
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  mysql: {}
  data: {}
  conf: {}